### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by sebastiankessel** [philosowaffle/vs-openapi-designer#40]
When attempting to "Preview" (In browser, panel or anything else) in **_MacOS Monterey_** a File not Found error (see below). The files are in their proper directory. In fact, ctrl-click on the reference on the yml itself sends me to the proper reference.

Folder

![image](https://user-images.githubusercontent.com/1382902/138963401-2c7fa869-ca41-47a1-b219-a8ac306bf2e3.png)

Expanding the "Common" folder

![image](https://user-images.githubusercontent.com/1382902/138963540-d6ea6aab-0972-4ac8-a9a1-ce039cfda740.png)

Sample line on how the reference is coded 

```
$ref: 'domain/common/elemental-types.yml#/components/schemas/person-name-info'
```

**Error Message**

  ```

There was an error while processing your files. Please fix the error and save the file.

  
{
  "errno": -2,
  "code": "ENOENT",
  "syscall": "open",
  "path": "///Users/sebastiankessel/IdeaProjects/CodeScience/XXX/domain/domain/common/elemental-types.yml",
  "name": "Error",
  "message": "Error opening file \"///Users/sebastiankessel/IdeaProjects/CodeScience/XXX/domain/domain/common/elemental-types.yml\"
ENOENT: no such file or directory, open '///Users/sebastiankessel/IdeaProjects/CodeScience/XXX/domain/domain/common/elemental-types.yml'",
  "stack": "Error: Error opening file \"///Users/sebastiankessel/IdeaProjects/CodeScience/XXX/domain/domain/common/elemental-types.yml\"
ENOENT: no such file or directory, open '///Users/sebastiankessel/IdeaProjects/CodeScience/XXX/domain/domain/common/elemental-types.yml
 at ReadFileContext.callback (/Users/sebastiankessel/.vscode/extensions/philosowaffle.openapi-designer-0.3.0/node_modules/json-schema-ref-parser/lib/resolvers/file.js:52:20
 at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13
\nError: ENOENT: no such file or directory, open '///Users/sebastiankessel/IdeaProjects/CodeScience/XXX/domain/domain/common/elemental-types.yml'"
}
```

**Comment by ragnarokkrr** [comment]
Same here but it's happening even without external file references.
